-- Database schema for Next.js Chat App
-- Execute this SQL code in your Supabase SQL Editor to prepare your database.

-- 1. Create the rooms table
create table if not exists public.rooms (
  id text primary key, -- Custom short-code ID (generated by nanoid on server-side)
  name text not null,  -- Display name of the room
  description text,
  icon_name text default 'Home01Icon',
  privacy text default 'public',
  owner text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- 2. Create the messages table
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  room_id text references public.rooms(id) on delete cascade not null,
  author text not null, -- Display name chosen by the message sender
  text text not null,   -- Message content
  created_at timestamptz default timezone('utc'::text, now()) not null,
  likes text[] default '{}'::text[] not null, -- Usernames who liked this message
  reply_to_id uuid references public.messages(id) on delete set null
);

-- Enable Row Level Security (RLS)
alter table public.rooms enable row level security;
alter table public.messages enable row level security;

-- 3. Drop existing policies if they exist (to make the script re-runnable/idempotent)
drop policy if exists "Allow public read access to rooms" on public.rooms;
drop policy if exists "Allow public insert access to rooms" on public.rooms;
drop policy if exists "Allow public read access to messages" on public.rooms;
drop policy if exists "Allow public read access to messages table" on public.messages;
drop policy if exists "Allow public insert access to messages table" on public.messages;
drop policy if exists "Allow public update access to messages table" on public.messages;

-- 4. Create Policies to allow public read/write access
create policy "Allow public read access to rooms" 
  on public.rooms for select using (true);

create policy "Allow public insert access to rooms" 
  on public.rooms for insert with check (true);

create policy "Allow public read access to messages table"
  on public.messages for select using (true);

create policy "Allow public insert access to messages table"
  on public.messages for insert with check (true);

create policy "Allow public update access to messages table"
  on public.messages for update using (true);

-- 5. Enable Realtime replication for the messages table
-- Check and create the 'supabase_realtime' publication if it doesn't exist
do $$
begin
  if not exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    create publication supabase_realtime;
  end if;
end
$$;

-- Safely add 'public.messages' to the publication if it's not already there
do $$
begin
  if not exists (
    select 1 
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    where pr.prpubid = (select oid from pg_publication where pubname = 'supabase_realtime')
      and c.relname = 'messages'
      and n.nspname = 'public'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end
$$;
